#!/bin/zsh

BUILD_EMSCRIPTEN=false

if (( $# == 2 )); then
    BUILD_EMSCRIPTEN=true
    EMSCRIPTEN_PREFIX=$2
    echo "Emscripten prefix: " $EMSCRIPTEN_PREFIX
fi

if (( $# < 1 )); then
    echo "Usage: ./build.sh <path_to_repositories>"
    exit 0
fi

REPOSITORY_PREFIX=$1
echo "Repository prefix: " $REPOSITORY_PREFIX

CORRADE_PREFIX=${REPOSITORY_PREFIX}"/corrade"
MAGNUM_PREFIX=${REPOSITORY_PREFIX}"/magnum"
MAGNUM_EXTRAS_PREFIX=${REPOSITORY_PREFIX}"/magnum-extras"
MAGNUM_PLUGINS_PREFIX=${REPOSITORY_PREFIX}"/magnum-plugins"
MAGNUM_INTEGRATION_PREFIX=${REPOSITORY_PREFIX}"/magnum-integration"

SDL2_BUILD_PREFIX="build"
EMSCRIPTEN_BUILD_PREFIX="build-emscripten"

echo CORRADE_PREFIX: $CORRADE_PREFIX
echo MAGNUM_PREFIX: $MAGNUM_PREFIX
echo MAGNUM_EXTRAS_PREFIX: $MAGNUM_EXTRAS_PREFIX


# Corrade
cd $CORRADE_PREFIX
rm -rf $SDL2_BUILD_PREFIX
mkdir $SDL2_BUILD_PREFIX
cd $SDL2_BUILD_PREFIX

cmake -DCMAKE_BUILD_TYPE=Release ..

make -j
sudo make install

# Magnum
cd $MAGNUM_PREFIX
rm -rf $SDL2_BUILD_PREFIX
mkdir $SDL2_BUILD_PREFIX
cd $SDL2_BUILD_PREFIX

cmake -DCMAKE_BUILD_TYPE=Release -DWITH_AUDIO=ON -DWITH_DEBUGTOOLS=ON -DWITH_GL=ON -DWITH_MESHTOOLS=ON -DWITH_PRIMITIVES=ON -DWITH_SCENEGRAPH=ON -DWITH_SHADERS=ON -DWITH_TEXT=ON -DWITH_TEXTURETOOLS=ON -DWITH_TRADE=ON -DWITH_SDL2APPLICATION=ON -DWITH_ANYAUDIOIMPORTER=ON -DWITH_ANYIMAGECONVERTER=ON -DWITH_ANYIMAGEIMPORTER=ON -DWITH_ANYSCENEIMPORTER=ON -DWITH_MAGNUMFONT=ON -DWITH_MAGNUMFONTCONVERTER=ON -DWITH_OBJIMPORTER=ON -DWITH_TGAIMPORTER=ON -DWITH_TGAIMAGECONVERTER=ON -DWITH_WAVAUDIOIMPORTER=ON -DWITH_GL_INFO=ON -DWITH_AL_INFO=ON ..

make -j
sudo make install

# Magnum plugins
cd $MAGNUM_PLUGINS_PREFIX
rm -rf $SDL2_BUILD_PREFIX
mkdir $SDL2_BUILD_PREFIX
cd $SDL2_BUILD_PREFIX
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_OPENGEXIMPORTER=ON -DWITH_DDSIMPORTER=ON -DWITH_STBIMAGECONVERTER=ON -DWITH_STBIMAGEIMPORTER=ON -DWITH_STBTRUETYPEFONT=ON ..

make -j
sudo make install

# Magnum extras
cd $MAGNUM_EXTRAS_PREFIX
rm -rf $SDL2_BUILD_PREFIX
mkdir $SDL2_BUILD_PREFIX
cd $SDL2_BUILD_PREFIX
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_UI=ON -DWITH_UI_GALLERY=ON ..

make -j
sudo make install

# Magnum integration
cd $MAGNUM_INTEGRATION_PREFIX
rm -rf $SDL2_BUILD_PREFIX
mkdir $SDL2_BUILD_PREFIX
cd $SDL2_BUILD_PREFIX
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_IMGUI=ON -DIMGUI_DIR=$REPOSITORY_PREFIX/imgui ..

make -j
sudo make install

if [ "$BUILD_EMSCRIPTEN" = true ]; then

  cd $CORRADE_PREFIX
  rm -rf $EMSCRIPTEN_BUILD_PREFIX
  mkdir $EMSCRIPTEN_BUILD_PREFIX
  cd $EMSCRIPTEN_BUILD_PREFIX
  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten-wasm.cmake" -DCMAKE_INSTALL_PREFIX=$EMSCRIPTEN_PREFIX ..
  make -j
  make install

  cd $MAGNUM_PREFIX
  rm -rf $EMSCRIPTEN_BUILD_PREFIX
  mkdir $EMSCRIPTEN_BUILD_PREFIX
  cd $EMSCRIPTEN_BUILD_PREFIX

  cmake -DCMAKE_BUILD_TYPE=Release -DWITH_AUDIO=ON -DWITH_DEBUGTOOLS=ON -DWITH_GL=ON -DWITH_MESHTOOLS=ON -DWITH_PRIMITIVES=ON -DWITH_SCENEGRAPH=ON -DWITH_SHADERS=ON -DWITH_TEXT=ON -DWITH_TEXTURETOOLS=ON -DWITH_TRADE=ON -DWITH_SDL2APPLICATION=ON -DWITH_ANYAUDIOIMPORTER=ON -DWITH_ANYIMAGECONVERTER=ON -DWITH_ANYIMAGEIMPORTER=ON -DWITH_ANYSCENEIMPORTER=ON -DWITH_MAGNUMFONT=ON -DWITH_MAGNUMFONTCONVERTER=ON -DWITH_OBJIMPORTER=ON -DWITH_TGAIMPORTER=ON -DWITH_TGAIMAGECONVERTER=ON -DWITH_WAVAUDIOIMPORTER=ON -DWITH_GL_INFO=ON -DWITH_AL_INFO=ON -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten-wasm.cmake" -DCMAKE_INSTALL_PREFIX=$EMSCRIPTEN_PREFIX -DTARGET_GLES2=OFF ..
  make -j
  make install

  cd $MAGNUM_PLUGINS_PREFIX
  rm -rf $EMSCRIPTEN_BUILD_PREFIX
  mkdir $EMSCRIPTEN_BUILD_PREFIX
  cd $EMSCRIPTEN_BUILD_PREFIX
  cmake -DCMAKE_BUILD_TYPE=Release -DWITH_OPENGEXIMPORTER=ON -DWITH_DDSIMPORTER=ON -DWITH_STBIMAGECONVERTER=ON -DWITH_STBIMAGEIMPORTER=ON -DWITH_STBTRUETYPEFONT=ON -DBUILD_PLUGINS_STATIC=ON -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten-wasm.cmake" -DCMAKE_INSTALL_PREFIX=$EMSCRIPTEN_PREFIX ..
  make -j
  make install

  cd $MAGNUM_EXTRAS_PREFIX
  rm -rf $EMSCRIPTEN_BUILD_PREFIX
  mkdir $EMSCRIPTEN_BUILD_PREFIX
  cd $EMSCRIPTEN_BUILD_PREFIX
  cmake -DCMAKE_BUILD_TYPE=Release -DWITH_UI=ON -DWITH_UI_GALLERY=ON -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten-wasm.cmake" -DCMAKE_INSTALL_PREFIX=$EMSCRIPTEN_PREFIX ..
  make -j
  make install

  # Magnum integration
  cd $MAGNUM_INTEGRATION_PREFIX
  rm -rf $EMSCRIPTEN_BUILD_PREFIX
  mkdir $EMSCRIPTEN_BUILD_PREFIX
  cd $EMSCRIPTEN_BUILD_PREFIX
  cmake -DCMAKE_BUILD_TYPE=Release -DWITH_IMGUI=ON -DIMGUI_DIR=$REPOSITORY_PREFIX/imgui -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten-wasm.cmake" -DCMAKE_INSTALL_PREFIX=$EMSCRIPTEN_PREFIX ..

  make -j
  make install
fi
